#!/bin/bash

## start pd
sudo puredata -nogui -noadc -rt /home/pi/nameofpatch.pd  &


## the stuff below is needed only if/when using adc2FUDI:

## pull up the GPIO for buttons: 
# sudo python /home/pi/pullup.py
## pause a little
# sleep 5
## start the ADC + interrupts
# sudo /home/pi/PD/adc2FUDI 127.0.0.1 54321 5 &
