#!/bin/bash

# load the spi module, just to make sure
sudo modprobe spi-bcm2708
# pull up the GPIO [buttons 1-3]
sudo python /home/pi/pullup.py
# start pd
sudo puredata -nogui -noadc -audiooutdev 0 /home/pi/PD/pv.pd  &
# pause a little
sleep 5
# start the ADC + interrupts
sudo /home/pi/PD/adc2FUDI 127.0.0.1 54321 5 &
