#!/bin/bash 

## Stop the ntp service
sudo service ntp stop

## Stop the triggerhappy service
sudo service triggerhappy stop

## Stop the dbus service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
sudo service dbus stop

## Remount /dev/shm to prevent memory allocation errors
sudo mount -o remount,size=128M /dev/shm

## set CPU scaling governor to performance (zero et al.)
echo -n performance | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

## set CPU scaling governor to performance (pi2, pi3)
#for cpu in /sys/devices/system/cpu/cpu[0-9]*; do 
#	echo -n performance | sudo tee $cpu/cpufreq/scaling_governor 
#done

exit
