#!/bin/bash 

## Stop the ntp service
sudo service ntp stop

## Stop the triggerhappy service
sudo service triggerhappy stop

## Stop the dbus service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
sudo service dbus stop

## Remount /dev/shm to prevent memory allocation errors
sudo mount -o remount,size=128M /dev/shm

## set CPU scaling governor to performance (pi2, pi3)
for cpu in /sys/devices/system/cpu/cpu[0-9]*; do
	echo -n performance | sudo tee $cpu/cpufreq/scaling_governor 
done

# master volume
amixer cset numid=1 110
# capture volume
amixer cset numid=3 31
# line capture switch
amixer cset numid=4 on
#  HiFi playback switch
amixer cset numid=13 on
# save
alsactl store

exit

